
[character]
success_symbol = "[â—](bold green)"
error_symbol = "[â—‹](bold red)"

[cmd_duration]
disabled = true

[conda]
style = "yellow"

[directory]
style = "blue"
truncation_symbol = ".../"

[git_branch]
style = "blue"

[git_status]
style = "red"

[package]
disabled = true

[python]
style = "yellow"

[quarto]
disabled = true

[rlang]
disabled = true

[shell]
disabled = false
format = "[$indicator]($style)"
fish_indicator = "ğŸŸ "
bash_indicator = ""
