#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[ui]
pager = ":builtin"
default-command = [
  "log", "--revisions", "heads(@::) | descendants(@, 3) | ancestors(@, 3)",
  "--no-pager"
]

[aliases]
sum = ["show", "--summary", "--no-pager"]
heads = ["log", "--revisions", "heads(all())"]

[user]
name = "Nick Ulle"
email = "nick.ulle@gmail.com"

[signing]
behavior = "own"
backend = "ssh"
key = "/home/nick/.ssh/zen.pub"
